name: fraud-detector
port: 8000

commands:
  - "gunicorn --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 0 --bind 0.0.0.0:8000 deployments.api.app:app"

dependencies:
  pypi:
    outerbounds: ""
    scikit-learn: ""
    pandas: ""
    numpy: ""
    pyarrow: ""
    requests: ""
    fastapi: ""
    uvicorn: ""
    gunicorn: ""

compute_pools:
  - c5-2x-deployment

auth:
  type: API
